Handle empty (bad) command line call better
Previously, if cutt was called via the command line without any
arguments (flags or subcommands), it spit out this error:

	AttributeError: 'Namespace' object has no attribute 'args_handler'

To the users, though, this is of no value since it doesn't tell them
what they did wrong. Handle such a call better by displaying a helpful
error message and exiting.